name: Downstream Workflow

on:
  push:
  
  repository_dispatch:
    types: [start-downstream-workflow]
    name: Buildcounter
 
env:
  BUILD_COUNTER_REPO: venkatsagiraju/Buildcounter
  BUILD_COUNTER_BRANCH: main
  BUILD_COUNTER_FILE: counter.txt
 
jobs:
  my_job:
    runs-on: windows-latest
    steps:
 
      - name: Read build counter
        id: read-counter
        run: |
          $filePath = "${{ env.BUILD_COUNTER_FILE }}"
          $version = "2022.4.3"
          if (Test-Path $filePath) {
            $lastBuildCounter = Get-Content $filePath
          } else {
            $lastBuildCounter = 0
          }
          Write-Host "::set-output name=last_build_counter::$lastBuildCounter"
 
      - name: Increment build counter
        id: increment-counter
        run: |
          $newBuildCounter = ${{ steps.read-counter.outputs.last_build_counter }} + 1 
          $newVersion = "$($version).$newBuildCounter"
          $filePath = "${{ env.BUILD_COUNTER_FILE }}"
          Set-Content -Path $filePath -Value $newBuildCounter
          Write-Host "::set-output name=new_version::$newVersion"

 
      - name: Commit and push build counter changes
        run: |
          git config user.name "venkatsagiraju"
          git config user.email "venkat_sagiraju@trimble.comcom"
          git add ${{ env.BUILD_COUNTER_FILE }}
          git commit -m "Increment build counter [skip ci]"
          git push
         
      - name: Print Build counter
        run: |
          echo "Build Counter: ${{ steps.increment-counter.outputs.new_version }}"
