name: Increment Counter

on:
  push:
    branches:
      - main

jobs:
  increment-counter:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Increment counter
        run: |
          # Read the current value from the file
          $current_value = Get-Content -Path counter.txt
          # Increment the current value
          $new_value = $current_value + 1
          # Write the new value back to the file
          Set-Content -Path counter.txt -Value $new_value

      - name: Configure Git
        run: |
          git config --global user.name "venkatsagiraju"
          git config --global user.email "venkat_sagiraju@trimble.com"

      - name: Commit changes
        run: |
          git add counter.txt
          git commit -m "Increment counter"
          git push origin main
