name: Increment Counter

on:
  push:
    branches:
      - main

jobs:
  increment-counter:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read current value
        id: read_counter
        run: echo "::set-output name=value::$(Get-Content counter.txt)"

      - name: Increment value
        id: increment_counter
        run: echo "::set-output name=value::$((${{steps.read_counter.outputs.value}} + 1))"

      - name: Update counter.txt
        run: Set-Content counter.txt ${{steps.increment_counter.outputs.value}}

      - name: Configure Git
        run: |
          git config --global user.name "venkatsagiraju"
          git config --global user.email "venkat_sagiraju@trimble.com"

      - name: Commit changes
        run: |
          git add counter.txt
          git commit -m "Increment counter"
          git push origin main
